language: rust
cache: cargo
rust:
  - beta

if: tag IS blank

before_install:
  - nvm install stable
  - npm install -g eslint

before_script:
  - rustup component add clippy
  - rustup component add rustfmt

script:
  - make release

before_deploy:
  - git config --local user.name "Justinas Stankevicius"
  - git config --local user.email "justinas@justinas.org"
  - export TRAVIS_TAG=${TRAVIS_TAG:-release-$(date -u +'%Y%m%dT%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG

deploy:
  provider: releases
  api_key:
    secure: "OzbbUdlFb79fAQkE7sMEqQAmld/fjJcEX38dRS8d2mg5i2Tc1WThU0GtyYjTo9PG8ftTLPy8sUIOceAvEUudQ51MhGKoLAheaD5aW92xj0vIcm4cUVZFptt+qvay+EzmERUwBtJNSsL+8SBIB+wdPisE1UFjRcxrofDdAYcVLy7nq4EVShxdkWYTSIpCKURHFbdKcVy1dDKHGpxAzZXILptIGdkKJ4fAJysC6/OjwYvQzQ7rYHhxgLiK6Wcq1FW/D1dsWhppxnsFdh1XU/oHGpNjindbHeeZZjWGM+kbu8KGeXMoN88f6Vp3jFFWbTePoq4K/9CHbWi+8nDlYTtQthVsmxygICP5bTFx9n9cHHf+ZmV32YDAXwaqG20sEqrJHde5aZxCPkx3uXYvv4y3wBXz9hoHQV5LSF4W/S3RCMdQhBnjclmCLBGUF/i+PT6jn1MgGCOe2MpAX0AcP5SbNSpivvKlr+Y9ylpaqw5yf9QpmF2ns2kFJ4pbj8mQqdoq6kH8suXOh1W0PnUq+ZhoT165sQPnAB9HQwG2rzMNLECJE+sIKFF+t509ML7+WHj9fe765qKNX/F3B6N6e0ll7cnyYTUJDMteXNNJAoFtdq6qtCkz1uOQmdXkLo1Ag7IpXASFzoTZLC3nERxLn90rlohUDdEZdGJfd2StQJtHhZg="
  file: release.tar.gz
  skip_cleanup: true
