env:
  browser: true
  es6: true
extends:
  - 'eslint:recommended'
globals:
  Vue: readonly
parserOptions:
  ecmaVersion: 2018
rules:
  brace-style:
    - error
  comma-dangle:
    - error
    - always-multiline
  dot-location:
    - error
    - property
  eqeqeq:
    - error
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  no-var:
    - error
  no-trailing-spaces:
    - error
  prefer-const:
    - error
  quotes:
    - error
    - single
  semi:
    - error
    - always
