[package]
authors = ["Justinas Stankevicius <justinas@justinas.org>"]
edition = "2018"
name = "oon_db"
version = "0.1.0"

[dependencies]
diesel = { version = "1.4", features = ["postgres", "r2d2", "uuidv07"] }
diesel_migrations = "1.4"
rand = "0.7"
uuid = "0.7"
