ALTER TABLE answers 
ADD COLUMN created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL
DEFAULT (now() AT TIME ZONE 'utc');

ALTER TABLE questions
ADD COLUMN created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL
DEFAULT (now() AT TIME ZONE 'utc');
