[package]
authors = ["Justinas Stankevicius <justinas@justinas.org>"]
edition = "2018"
name = "oon_scraper"
version = "0.1.0"

[dependencies]
reqwest = { version = "0.10.0-alpha.1", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = "0.2.0-alpha.5"
